from __future__ import annotations

from typing import Any, Dict, List, Optional, TYPE_CHECKING

from ..contracts import (
    FrameDiagnostics,
    FrameRecord,
    HandObservation,
    PoseObservation,
    SamplePayload,
)
from .arrays import extract_sample_arrays_from_records
from .rows import build_frame_rows_from_records

if TYPE_CHECKING:
    from ..pipeline.frame_step import FrameStepResult


def build_runtime_frame_record(
    *,
    frame_idx: int,
    ts_ms: int,
    dt_ms: int,
    left,
    right,
    left_score,
    right_score,
    left_score_gate,
    right_score_gate,
    src1,
    src2,
    hand1_state: str,
    hand2_state: str,
    hand1_is_anchor: bool,
    hand2_is_anchor: bool,
    left_reject_reason,
    right_reject_reason,
    pose_quality_left,
    pose_quality_right,
    hand_wrist_z_left,
    hand_wrist_z_right,
    sanity_dbg_left,
    sanity_dbg_right,
    sanity_stage_left,
    sanity_stage_right,
    track_age_left: int,
    track_age_right: int,
    track_reset_left: bool,
    track_reset_right: bool,
    tracker_left_ready: bool,
    tracker_right_ready: bool,
    tracker_last_score_left,
    tracker_last_score_right,
    tracker_last_ts_left,
    tracker_last_ts_right,
    swap_applied: bool,
    dedup_triggered: bool,
    dedup_removed: str,
    dedup_iou,
    dedup_dist_norm,
    track_ok_left: bool,
    track_ok_right: bool,
    sp_attempt_left: bool,
    sp_attempt_right: bool,
    rec_l: bool,
    rec_r: bool,
    sp_overlap_iou_val: float,
    overlap: bool,
    iou_hands,
    occlusion_iou,
    overlap_guard_pre: bool,
    overlap_guard: bool,
    overlap_freeze: bool,
    overlap_freeze_reason,
    overlap_freeze_side,
    overlap_iou_guard,
    overlap_iou_guard_src,
    overlap_z_hint,
    occlusion_z_diff,
    overlap_hand_z_diff,
    pose_side_ambiguous: bool,
    pose_side_reassign_ratio_eff: float,
    side_d_ll,
    side_d_lr,
    side_d_rl,
    side_d_rr,
    side_cost_current,
    side_cost_swap,
    side_pref_left,
    side_pref_right,
    side_ok_left_accept: bool,
    side_ok_right_accept: bool,
    occluded_L: bool,
    occluded_R: bool,
    occ_ttl_left: int,
    occ_ttl_right: int,
    occ_freeze_age_left: int,
    occ_freeze_age_right: int,
    occ_freeze_max_frames: int,
    occlusion_saved_1: bool,
    occlusion_saved_2: bool,
    missing_pre_occ_left: bool,
    missing_pre_occ_right: bool,
    occlusion_behind_diff,
    occlusion_samples_ok: bool,
    pose_wrist_dist_1,
    pose_wrist_dist_2,
    pose_wrist_z_world_left,
    pose_wrist_z_world_right,
    pose_wrist_z_img_left,
    pose_wrist_z_img_right,
    score_source: str,
    min_hand_score: float,
    hand_lo: float,
    hand_hi: float,
    anchor_score_eff: float,
    tracker_init_score_eff,
    tracker_update_score_eff,
    pose_dist_qual_min_eff,
    pose_xyz,
    pose_vis,
    pose_interpolated: bool,
    write_hand_mask: bool,
    left_roi,
    right_roi,
    sp_dbg_left,
    sp_dbg_right,
    sp_params_left,
    sp_params_right,
) -> FrameRecord:
    diagnostics = FrameDiagnostics(values={
        "hand_1_score": float(left_score) if left_score is not None else None,
        "hand_1_score_gate": float(left_score_gate) if left_score_gate is not None else None,
        "hand_1_source": src1,
        "hand_1_state": hand1_state,
        "hand_1_is_anchor": bool(hand1_is_anchor),
        "hand_1_reject_reason": left_reject_reason,
        "hand_1_pose_quality": float(pose_quality_left) if pose_quality_left is not None else None,
        "hand_1_wrist_z": float(hand_wrist_z_left) if hand_wrist_z_left is not None else None,
        "hand_1_sanity_scale_ratio": sanity_dbg_left.get("scale_ratio") if sanity_dbg_left else None,
        "hand_1_sanity_wrist_jump": sanity_dbg_left.get("wrist_jump_dist") if sanity_dbg_left else None,
        "hand_1_sanity_bone_max_err": sanity_dbg_left.get("bone_max_rel_err") if sanity_dbg_left else None,
        "hand_1_sanity_bone_worst": sanity_dbg_left.get("bone_worst") if sanity_dbg_left else None,
        "hand_1_sanity_stage": sanity_stage_left,
        "hand_1_track_age": int(track_age_left),
        "hand_1_track_reset": bool(track_reset_left),
        "hand_1_tracker_ready": bool(tracker_left_ready),
        "hand_1_tracker_last_score": float(tracker_last_score_left) if tracker_last_score_left is not None else None,
        "hand_1_tracker_last_ts": float(tracker_last_ts_left) if tracker_last_ts_left is not None else None,
        "hand_2_score": float(right_score) if right_score is not None else None,
        "hand_2_score_gate": float(right_score_gate) if right_score_gate is not None else None,
        "hand_2_source": src2,
        "hand_2_state": hand2_state,
        "hand_2_is_anchor": bool(hand2_is_anchor),
        "hand_2_reject_reason": right_reject_reason,
        "hand_2_pose_quality": float(pose_quality_right) if pose_quality_right is not None else None,
        "hand_2_wrist_z": float(hand_wrist_z_right) if hand_wrist_z_right is not None else None,
        "hand_2_sanity_scale_ratio": sanity_dbg_right.get("scale_ratio") if sanity_dbg_right else None,
        "hand_2_sanity_wrist_jump": sanity_dbg_right.get("wrist_jump_dist") if sanity_dbg_right else None,
        "hand_2_sanity_bone_max_err": sanity_dbg_right.get("bone_max_rel_err") if sanity_dbg_right else None,
        "hand_2_sanity_bone_worst": sanity_dbg_right.get("bone_worst") if sanity_dbg_right else None,
        "hand_2_sanity_stage": sanity_stage_right,
        "hand_2_track_age": int(track_age_right),
        "hand_2_track_reset": bool(track_reset_right),
        "hand_2_tracker_ready": bool(tracker_right_ready),
        "hand_2_tracker_last_score": float(tracker_last_score_right) if tracker_last_score_right is not None else None,
        "hand_2_tracker_last_ts": float(tracker_last_ts_right) if tracker_last_ts_right is not None else None,
        "swap_applied": bool(swap_applied),
        "dedup_triggered": bool(dedup_triggered),
        "dedup_removed": dedup_removed,
        "dedup_iou": float(dedup_iou) if dedup_iou is not None else None,
        "dedup_dist_norm": float(dedup_dist_norm) if dedup_dist_norm is not None else None,
        "hand_1_track_ok": bool(track_ok_left),
        "hand_2_track_ok": bool(track_ok_right),
        "hand_1_sp_attempted": bool(sp_attempt_left),
        "hand_2_sp_attempted": bool(sp_attempt_right),
        "hand_1_sp_recovered": bool(rec_l),
        "hand_2_sp_recovered": bool(rec_r),
        "sp_overlap_iou": round(float(sp_overlap_iou_val), 4),
        "overlap_iou_sp": float(sp_overlap_iou_val),
        "sp_overlap": bool(overlap),
        "iou_hands": float(iou_hands) if iou_hands is not None else None,
        "overlap_iou_ref": float(occlusion_iou) if occlusion_iou is not None else None,
        "overlap_guard_pre": bool(overlap_guard_pre),
        "overlap_guard": bool(overlap_guard),
        "overlap_freeze": bool(overlap_freeze),
        "overlap_freeze_reason": overlap_freeze_reason,
        "overlap_freeze_side": overlap_freeze_side,
        "overlap_iou_guard": float(overlap_iou_guard) if overlap_iou_guard is not None else None,
        "overlap_iou_guard_src": overlap_iou_guard_src,
        "overlap_z_hint": float(overlap_z_hint) if overlap_z_hint is not None else None,
        "overlap_z_abs": float(abs(occlusion_z_diff)) if occlusion_z_diff is not None else None,
        "overlap_hand_z_diff": float(overlap_hand_z_diff) if overlap_hand_z_diff is not None else None,
        "pose_side_ambiguous": bool(pose_side_ambiguous),
        "pose_side_ratio": float(pose_side_reassign_ratio_eff),
        "side_d_ll": float(side_d_ll) if side_d_ll is not None else None,
        "side_d_lr": float(side_d_lr) if side_d_lr is not None else None,
        "side_d_rl": float(side_d_rl) if side_d_rl is not None else None,
        "side_d_rr": float(side_d_rr) if side_d_rr is not None else None,
        "side_cost_current": float(side_cost_current) if side_cost_current is not None else None,
        "side_cost_swap": float(side_cost_swap) if side_cost_swap is not None else None,
        "side_pref_left": side_pref_left,
        "side_pref_right": side_pref_right,
        "side_ok_1": bool(side_ok_left_accept),
        "side_ok_2": bool(side_ok_right_accept),
        "occluded_1": bool(occluded_L),
        "occluded_2": bool(occluded_R),
        "occluded_1_ttl": int(occ_ttl_left),
        "occluded_2_ttl": int(occ_ttl_right),
        "occlusion_freeze_age_1": int(occ_freeze_age_left),
        "occlusion_freeze_age_2": int(occ_freeze_age_right),
        "occlusion_freeze_max": int(occ_freeze_max_frames),
        "occlusion_saved_1": bool(occlusion_saved_1),
        "occlusion_saved_2": bool(occlusion_saved_2),
        "missing_pre_occ_1": bool(missing_pre_occ_left),
        "missing_pre_occ_2": bool(missing_pre_occ_right),
        "occlusion_iou": float(occlusion_iou) if occlusion_iou is not None else None,
        "occlusion_z_diff": float(occlusion_z_diff) if occlusion_z_diff is not None else None,
        "occlusion_behind_diff": float(occlusion_behind_diff) if occlusion_behind_diff is not None else None,
        "occlusion_samples_ok": bool(occlusion_samples_ok),
        "pose_wrist_dist_1": float(pose_wrist_dist_1) if pose_wrist_dist_1 is not None else None,
        "pose_wrist_dist_2": float(pose_wrist_dist_2) if pose_wrist_dist_2 is not None else None,
        "pose_wrist_z_left_world": float(pose_wrist_z_world_left) if pose_wrist_z_world_left is not None else None,
        "pose_wrist_z_right_world": float(pose_wrist_z_world_right) if pose_wrist_z_world_right is not None else None,
        "pose_wrist_z_left_img": float(pose_wrist_z_img_left) if pose_wrist_z_img_left is not None else None,
        "pose_wrist_z_right_img": float(pose_wrist_z_img_right) if pose_wrist_z_img_right is not None else None,
        "score_source": score_source,
        "min_hand_score": float(min_hand_score),
        "hand_score_lo": float(hand_lo),
        "hand_score_hi": float(hand_hi),
        "anchor_score": float(anchor_score_eff),
        "tracker_init_score": float(tracker_init_score_eff) if tracker_init_score_eff is not None else None,
        "tracker_update_score": float(tracker_update_score_eff) if tracker_update_score_eff is not None else None,
        "pose_dist_qual_min": float(pose_dist_qual_min_eff) if pose_dist_qual_min_eff is not None else None,
        "pose_interpolated": bool(pose_interpolated),
    })
    extras: Dict[str, Any] = {}
    if write_hand_mask:
        h1_ok = 1 if left is not None else 0
        h2_ok = 1 if right is not None else 0
        extras["hand_mask"] = [h1_ok, h2_ok]
    if left_roi is not None:
        extras["hand 1_sp_roi_px"] = [int(left_roi[0]), int(left_roi[1]), int(left_roi[2]), int(left_roi[3])]
    if right_roi is not None:
        extras["hand 2_sp_roi_px"] = [int(right_roi[0]), int(right_roi[1]), int(right_roi[2]), int(right_roi[3])]
    if sp_dbg_left is not None:
        extras["hand 1_sp_center_hint_px"] = sp_dbg_left.get("center_hint_px")
        extras["hand 1_sp_debug"] = sp_dbg_left
        extras["hand 1_sp_params"] = sp_params_left
    if sp_dbg_right is not None:
        extras["hand 2_sp_center_hint_px"] = sp_dbg_right.get("center_hint_px")
        extras["hand 2_sp_debug"] = sp_dbg_right
        extras["hand 2_sp_params"] = sp_params_right
    return FrameRecord(
        frame_idx=int(frame_idx),
        ts_ms=int(ts_ms),
        dt_ms=int(dt_ms),
        hand_1=HandObservation(
            landmarks=left,
            score=float(left_score) if left_score is not None else None,
            score_gate=float(left_score_gate) if left_score_gate is not None else None,
            source=src1,
            state=hand1_state,
            is_anchor=bool(hand1_is_anchor),
            reject_reason=left_reject_reason,
            pose_quality=float(pose_quality_left) if pose_quality_left is not None else None,
            wrist_z=float(hand_wrist_z_left) if hand_wrist_z_left is not None else None,
            track_age=int(track_age_left),
            track_reset=bool(track_reset_left),
            tracker_ready=bool(tracker_left_ready),
            tracker_last_score=float(tracker_last_score_left) if tracker_last_score_left is not None else None,
            tracker_last_ts=float(tracker_last_ts_left) if tracker_last_ts_left is not None else None,
        ),
        hand_2=HandObservation(
            landmarks=right,
            score=float(right_score) if right_score is not None else None,
            score_gate=float(right_score_gate) if right_score_gate is not None else None,
            source=src2,
            state=hand2_state,
            is_anchor=bool(hand2_is_anchor),
            reject_reason=right_reject_reason,
            pose_quality=float(pose_quality_right) if pose_quality_right is not None else None,
            wrist_z=float(hand_wrist_z_right) if hand_wrist_z_right is not None else None,
            track_age=int(track_age_right),
            track_reset=bool(track_reset_right),
            tracker_ready=bool(tracker_right_ready),
            tracker_last_score=float(tracker_last_score_right) if tracker_last_score_right is not None else None,
            tracker_last_ts=float(tracker_last_ts_right) if tracker_last_ts_right is not None else None,
        ),
        pose=PoseObservation(
            landmarks=pose_xyz,
            visibility=pose_vis,
            interpolated=bool(pose_interpolated),
        ),
        both_hands=bool(left is not None and right is not None),
        diagnostics=diagnostics,
        extras=extras,
    )


def build_frame_record(step: "FrameStepResult") -> FrameRecord:
    return step.record


def _resolved_pose_indices(meta_header: Dict[str, Any], pose_joint_count: int) -> List[int]:
    raw = meta_header.get("pose_indices")
    if isinstance(raw, list):
        return [int(x) for x in raw]
    if pose_joint_count <= 0:
        return []
    return list(range(int(pose_joint_count)))


def build_sample_payload(
    *,
    sample_id: str,
    slug: str,
    source_video: str,
    meta_header: Dict[str, Any],
    frame_records: List[FrameRecord],
    frame_records_pp: Optional[List[FrameRecord]],
    manifest_dict: Dict[str, Any],
    segment_meta: Optional[Dict[str, Any]],
    fps: float,
    runtime_metrics: Optional[Dict[str, Any]] = None,
) -> SamplePayload:
    raw_arrays = extract_sample_arrays_from_records(frame_records, meta_header=meta_header)
    pp_arrays = (
        extract_sample_arrays_from_records(frame_records_pp, meta_header=meta_header)
        if frame_records_pp is not None else None
    )
    pose_joint_count = int(raw_arrays["pose_xyz"].shape[1]) if raw_arrays.get("pose_xyz") is not None else 0
    pose_indices = _resolved_pose_indices(meta_header, pose_joint_count)
    sample_attrs = {
        "sample_id": str(sample_id),
        "source_video": str(source_video).replace("\\", "/"),
        "slug": str(slug),
        "segment_start": int(segment_meta.get("start")) if segment_meta and segment_meta.get("start") is not None else None,
        "segment_end": int(segment_meta.get("end")) if segment_meta and segment_meta.get("end") is not None else None,
        "coords_mode": str(meta_header.get("coords", "image")),
        "pose_indices": pose_indices,
        "num_frames": int(len(frame_records)),
        "fps": float(fps),
        "fps_est": float(manifest_dict.get("fps_est", fps or 0.0) or 0.0),
        "postprocess_enabled": bool(pp_arrays is not None),
    }
    video_row = dict(manifest_dict)
    video_row.update(
        {
            "split": str(segment_meta.get("split")) if segment_meta and segment_meta.get("split") is not None else None,
            "seg_uid": str(segment_meta.get("seg_uid")) if segment_meta and segment_meta.get("seg_uid") is not None else None,
            "video_id": str(segment_meta.get("video_id")) if segment_meta and segment_meta.get("video_id") is not None else None,
            "segment_start": int(segment_meta.get("start")) if segment_meta and segment_meta.get("start") is not None else None,
            "segment_end": int(segment_meta.get("end")) if segment_meta and segment_meta.get("end") is not None else None,
            "segment_length": int(segment_meta.get("length")) if segment_meta and segment_meta.get("length") is not None else None,
            "segment_dataset": str(segment_meta.get("dataset")) if segment_meta and segment_meta.get("dataset") is not None else None,
            "segment_label": str(segment_meta.get("label")) if segment_meta and segment_meta.get("label") is not None else None,
            "pose_joint_count": int(pose_joint_count),
            "coords_mode": str(sample_attrs["coords_mode"]),
            "postprocess_enabled": bool(pp_arrays is not None),
        }
    )
    return SamplePayload(
        sample_id=str(sample_id),
        slug=str(slug),
        source_video=str(source_video).replace("\\", "/"),
        sample_attrs=sample_attrs,
        video_row=video_row,
        frame_rows=build_frame_rows_from_records(frame_records),
        raw_arrays=raw_arrays,
        pp_arrays=pp_arrays,
        runtime_metrics=dict(runtime_metrics) if runtime_metrics is not None else None,
    )
