from __future__ import annotations

POSE_WRIST_REJECT_SCALE = 1.5
POSE_WRIST_REJECT_MIN_IMAGE = 0.04
POSE_WRIST_REJECT_MIN_WORLD = 0.08
POSE_WRIST_MIN_VIS = 0.25
POSE_WRIST_OFF_MARGIN = 0.08
POSE_SIDE_REASSIGN_RATIO = 0.85
POSE_WRIST_CROSS_SCALE = 1.1
CROSS_OCCLUSION_FRAMES = 6
OCCLUSION_FREEZE_MAX_FRAMES = 6
OVERLAP_Z_MIN = 0.01
OCCLUSION_HYST_FRAMES = 4  # keep occluded state for a few frames if overlap persists

# MediaPipe Constants
MP_POSE_LEFT_WRIST_IDX = 15
MP_POSE_RIGHT_WRIST_IDX = 16
MP_POSE_NUM_LANDMARKS = 33

# Hand Detection Constants
HAND_MIN_DETECTION_CONFIDENCE = 0.5
HAND_MIN_TRACKING_CONFIDENCE = 0.5
HAND_SP_MIN_DETECTION = 0.05
HAND_SP_MIN_TRACKING = 0.05

# Occlusion Constants
OCCLUSION_IOU_THRESHOLD_WORLD = 0.02
OCCLUSION_IOU_THRESHOLD_IMAGE = 0.05
OCCLUSION_Z_THRESHOLD_WORLD = 0.015
OCCLUSION_Z_THRESHOLD_IMAGE = 0.012
OCCLUSION_HYST_IOU_SCALE = 0.35
OVERLAP_GUARD_IOU = 0.05

# Dedup Constants
DEDUP_DIST_SCALE = 0.25
DEDUP_D0_SCALE = 0.35
DEDUP_IOU_THRESHOLD = 0.80
MIN_QUALITY = 0.65
DELTA_QUALITY = 0.20

# Second Pass Constants
SP_MIN_DET_MULTIPLIER = 0.66  # multiplier for min_det in second pass
SP_MIN_TRACK_MULTIPLIER = 0.5  # multiplier for min_track in second pass

MP_HAND_NUM_LANDMARKS = 21
